package utility;

import artexCore.Vertex;
/**
 * Statics will save most used variables
 *
 * @author Amirhossein Azimyzadeh
 * */
public class Statics {
    public final static String FILE_SIGNATURE = "# Generated by Artex library \n";
    public final static Vertex ORIGIN_VERTEX = new Vertex(0.0f,0.0f,0.0f);
}
